"""Phase 2 seed data — a small, fully synthetic set of sample funds.

IMPORTANT — READ BEFORE TOUCHING THIS FILE
============================================
Every AMC, fund family, scheme, security, manager, NAV value and holding
weight in this file is FICTIONAL. None of it comes from AMFI, SEBI, NSE, RBI
or any AMC. It exists only to exercise the database schema end to end during
development (Rule 2: never fabricate real financial data; if real data is
unavailable, use clearly labelled mock data and never mix it with production
data).

How that rule is enforced here, concretely:
- AMC/fund-family/scheme names are invented ("Northbridge", "Meridian") —
  they do not resemble any real AMC or scheme name.
- All identifiers (AMFI codes, ISINs) are prefixed "SAMPLE-" so they can
  never collide with, or be mistaken for, a real identifier ingested later
  by the Phase 3 pipeline.
- The single `data_sources` row this script creates is named and typed
  accordingly ("manual" / "Synthetic Sample Data Generator"), so every NAV,
  benchmark and holdings row traces back to a source that says exactly what
  it is.
- NAV and benchmark histories are generated by a seeded random walk
  (`numpy.random.default_rng(SEED)`), not copied from any real fund or
  index — this is simulation, not data entry.

This script is idempotent: it checks for its own sample AMCs before
inserting anything, so re-running it is a no-op unless --reset is passed.
Once Phase 3 (real NAV ingestion) exists, this sample data must never be
presented to a user as if it were real; do not point production ingestion
runs at the same rows without first clearing this seed set.

Usage:
    cd backend && source .venv/bin/activate
    python ../database/seeds/seed_sample_data.py [--reset]
"""
from __future__ import annotations

import argparse
import os
import sys
from datetime import date, timedelta

import numpy as np

BACKEND_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "backend"))
if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

from app.core.database import SessionLocal  # noqa: E402
from app.models.reference import (  # noqa: E402
    AMC,
    Benchmark,
    FundFamily,
    FundManager,
    FundManagerHistory,
    MarketRegime,
    Scheme,
    SchemeVariant,
    Sector,
    Security,
)
from app.models.timeseries import (  # noqa: E402
    BenchmarkHistory,
    DataSource,
    NavHistory,
    PortfolioHolding,
    PortfolioSnapshot,
)

SEED = 42
SAMPLE_AMC_NAME = "Northbridge Asset Management (Sample Data)"
NAV_START_DATE = date(2021, 4, 1)
NAV_END_DATE = date(2025, 3, 31)


def business_days(start: date, end: date) -> list[date]:
    days = []
    d = start
    while d <= end:
        if d.weekday() < 5:  # Mon-Fri; not a real market-holiday calendar
            days.append(d)
        d += timedelta(days=1)
    return days


def simulate_gbm_series(rng: np.random.Generator, n: int, start_value: float,
                         annual_drift: float, annual_vol: float) -> np.ndarray:
    """Simple geometric-Brownian-motion path — a synthetic NAV/index generator,
    not a market model. daily_steps ~ 252 trading days/year."""
    dt = 1 / 252
    daily_drift = (annual_drift - 0.5 * annual_vol**2) * dt
    daily_shocks = rng.normal(daily_drift, annual_vol * np.sqrt(dt), size=n)
    log_path = np.cumsum(daily_shocks)
    return start_value * np.exp(log_path)


def already_seeded(db) -> bool:
    return db.query(AMC).filter(AMC.name == SAMPLE_AMC_NAME).first() is not None


def reset_sample_data(db) -> None:
    """Delete only rows created by this script (matched via the sample source /
    sample AMC names), never anything else."""
    amc_names = [SAMPLE_AMC_NAME, "Meridian Mutual Fund (Sample Data)"]
    amcs = db.query(AMC).filter(AMC.name.in_(amc_names)).all()
    if not amcs:
        return
    amc_ids = [a.id for a in amcs]
    families = db.query(FundFamily).filter(FundFamily.amc_id.in_(amc_ids)).all()
    family_ids = [f.id for f in families]
    schemes = db.query(Scheme).filter(Scheme.fund_family_id.in_(family_ids)).all()
    scheme_ids = [s.id for s in schemes]
    variants = db.query(SchemeVariant).filter(SchemeVariant.scheme_id.in_(scheme_ids)).all()
    variant_ids = [v.id for v in variants]
    snapshots = db.query(PortfolioSnapshot).filter(PortfolioSnapshot.scheme_id.in_(scheme_ids)).all()
    snapshot_ids = [s.id for s in snapshots]

    db.query(PortfolioHolding).filter(PortfolioHolding.snapshot_id.in_(snapshot_ids)).delete(synchronize_session=False)
    db.query(PortfolioSnapshot).filter(PortfolioSnapshot.id.in_(snapshot_ids)).delete(synchronize_session=False)
    db.query(NavHistory).filter(NavHistory.scheme_variant_id.in_(variant_ids)).delete(synchronize_session=False)
    db.query(FundManagerHistory).filter(FundManagerHistory.scheme_id.in_(scheme_ids)).delete(synchronize_session=False)
    db.query(SchemeVariant).filter(SchemeVariant.id.in_(variant_ids)).delete(synchronize_session=False)
    db.query(Scheme).filter(Scheme.id.in_(scheme_ids)).delete(synchronize_session=False)
    db.query(FundFamily).filter(FundFamily.id.in_(family_ids)).delete(synchronize_session=False)
    db.query(AMC).filter(AMC.id.in_(amc_ids)).delete(synchronize_session=False)

    db.query(BenchmarkHistory).filter(
        BenchmarkHistory.benchmark_id.in_(
            db.query(Benchmark.id).filter(Benchmark.name.like("%(Sample Series)"))
        )
    ).delete(synchronize_session=False)
    db.query(Benchmark).filter(Benchmark.name.like("%(Sample Series)")).delete(synchronize_session=False)

    db.query(FundManager).filter(FundManager.name.like("Sample Manager%")).delete(synchronize_session=False)
    db.query(Security).filter(Security.isin.like("SAMPLE-ISIN-%")).delete(synchronize_session=False)
    db.query(Sector).filter(Sector.name.like("Sample: %")).delete(synchronize_session=False)
    db.query(MarketRegime).filter(MarketRegime.name.like("Sample Regime%")).delete(synchronize_session=False)
    db.query(DataSource).filter(DataSource.name == "Synthetic Sample Data Generator").delete(synchronize_session=False)
    db.commit()
    print("Reset: removed previously seeded sample rows.")


def seed(db) -> None:
    rng = np.random.default_rng(SEED)
    days = business_days(NAV_START_DATE, NAV_END_DATE)
    n_days = len(days)

    source = DataSource(
        name="Synthetic Sample Data Generator",
        url=None,
        source_type="manual",
    )
    db.add(source)
    db.flush()

    # --- Sectors (one nested pair to exercise parent_sector_id) ---
    financials = Sector(name="Sample: Financial Services")
    it_sector = Sector(name="Sample: Information Technology")
    energy = Sector(name="Sample: Energy")
    consumer = Sector(name="Sample: Consumer Staples")
    healthcare = Sector(name="Sample: Healthcare")
    industrials = Sector(name="Sample: Industrials")
    db.add_all([financials, it_sector, energy, consumer, healthcare, industrials])
    db.flush()
    private_banks = Sector(name="Sample: Private Banks", parent_sector_id=financials.id)
    db.add(private_banks)
    db.flush()

    # --- Securities (fictitious companies) ---
    # Market-cap category is another fictional attribute of these fictional
    # companies (Rule 2) — assigned here by the same "clearly-labelled
    # sample data" logic as everything else in this file, not derived from
    # any real classification. None for the two bonds: market-cap doesn't
    # apply to debt instruments.
    securities_spec = [
        ("Sample Bank Corp Ltd", private_banks.id, "large_cap"),
        ("Sample Finserve Ltd", financials.id, "mid_cap"),
        ("Sample IT Solutions Ltd", it_sector.id, "large_cap"),
        ("Sample Software Systems Ltd", it_sector.id, "mid_cap"),
        ("Sample Energy Corp Ltd", energy.id, "large_cap"),
        ("Sample Refineries Ltd", energy.id, "large_cap"),
        ("Sample Consumer Goods Ltd", consumer.id, "large_cap"),
        ("Sample Foods Ltd", consumer.id, "mid_cap"),
        ("Sample Pharma Ltd", healthcare.id, "large_cap"),
        ("Sample Hospitals Ltd", healthcare.id, "mid_cap"),
        ("Sample Engineering Ltd", industrials.id, "mid_cap"),
        ("Sample Infra Ltd", industrials.id, "small_cap"),
        ("Sample Govt Security 7.26% 2033 (Sample Bond)", None, None),
        ("Sample NBFC Bond Series X (Sample Bond)", None, None),
    ]
    securities = {}
    for i, (name, sector_id, market_cap_category) in enumerate(securities_spec, start=1):
        sec = Security(
            isin=f"SAMPLE-ISIN-{i:04d}", name=name, sector_id=sector_id,
            market_cap_category=market_cap_category,
        )
        db.add(sec)
        securities[name] = sec
    db.flush()

    # --- Benchmarks ---
    bm_equity_large = Benchmark(name="Nifty 50 TRI (Sample Series)", index_code="SAMPLE-N50TRI")
    bm_equity_mid = Benchmark(name="Nifty Midcap 150 TRI (Sample Series)", index_code="SAMPLE-NMC150TRI")
    bm_debt = Benchmark(name="CRISIL Short Term Bond Index (Sample Series)", index_code="SAMPLE-CRISILSTB")
    db.add_all([bm_equity_large, bm_equity_mid, bm_debt])
    db.flush()

    bm_series = {
        bm_equity_large.id: simulate_gbm_series(rng, n_days, 10000.0, annual_drift=0.12, annual_vol=0.16),
        bm_equity_mid.id: simulate_gbm_series(rng, n_days, 10000.0, annual_drift=0.14, annual_vol=0.22),
        bm_debt.id: simulate_gbm_series(rng, n_days, 2000.0, annual_drift=0.065, annual_vol=0.03),
    }
    for bm_id, series in bm_series.items():
        db.bulk_save_objects([
            BenchmarkHistory(benchmark_id=bm_id, date=d, value=round(float(v), 4), source_id=source.id)
            for d, v in zip(days, series)
        ])

    # --- AMCs / fund families ---
    amc1 = AMC(name=SAMPLE_AMC_NAME)
    amc2 = AMC(name="Meridian Mutual Fund (Sample Data)")
    db.add_all([amc1, amc2])
    db.flush()

    family1 = FundFamily(amc_id=amc1.id, name="Northbridge Equity Fund Family")
    family2 = FundFamily(amc_id=amc2.id, name="Meridian Hybrid & Debt Fund Family")
    db.add_all([family1, family2])
    db.flush()

    # --- Fund managers ---
    mgr_a = FundManager(name="Sample Manager — A. Mehta")
    mgr_b = FundManager(name="Sample Manager — R. Iyer")
    mgr_c = FundManager(name="Sample Manager — S. Kapoor")
    db.add_all([mgr_a, mgr_b, mgr_c])
    db.flush()

    # --- Schemes ---
    scheme_bluechip = Scheme(
        fund_family_id=family1.id, benchmark_id=bm_equity_large.id,
        name="Northbridge Bluechip Equity Fund", category="Equity - Large Cap",
    )
    scheme_flexicap = Scheme(
        fund_family_id=family1.id, benchmark_id=bm_equity_large.id,
        name="Northbridge Flexi Cap Fund", category="Equity - Flexi Cap",
    )
    scheme_midcap = Scheme(
        fund_family_id=family2.id, benchmark_id=bm_equity_mid.id,
        name="Meridian Midcap Opportunities Fund", category="Equity - Mid Cap",
    )
    scheme_debt = Scheme(
        fund_family_id=family2.id, benchmark_id=bm_debt.id,
        name="Meridian Short Duration Debt Fund", category="Debt - Short Duration",
    )
    db.add_all([scheme_bluechip, scheme_flexicap, scheme_midcap, scheme_debt])
    db.flush()

    db.add_all([
        FundManagerHistory(scheme_id=scheme_bluechip.id, manager_id=mgr_a.id, start_date=date(2019, 6, 1), end_date=None),
        FundManagerHistory(scheme_id=scheme_flexicap.id, manager_id=mgr_a.id, start_date=date(2020, 1, 1), end_date=None),
        FundManagerHistory(scheme_id=scheme_midcap.id, manager_id=mgr_b.id, start_date=date(2018, 4, 1), end_date=date(2023, 3, 31)),
        FundManagerHistory(scheme_id=scheme_midcap.id, manager_id=mgr_c.id, start_date=date(2023, 4, 1), end_date=None),
        FundManagerHistory(scheme_id=scheme_debt.id, manager_id=mgr_c.id, start_date=date(2017, 9, 1), end_date=None),
    ])

    # --- Scheme variants (direct/regular x growth) + synthetic NAV ---
    # Direct plans carry a small, permanent expense-ratio edge over regular
    # plans (lower TER -> higher NAV growth over time) — this is a realistic
    # *mechanism*, not a copied real-world number; the edge size is an
    # illustrative assumption, not sourced from any factsheet.
    scheme_configs = [
        (scheme_bluechip, "BLC", 100.0, 0.12, 0.15),
        (scheme_flexicap, "FLX", 50.0, 0.13, 0.17),
        (scheme_midcap, "MID", 40.0, 0.15, 0.21),
        (scheme_debt, "DBT", 20.0, 0.062, 0.025),
    ]
    variants_by_scheme: dict[int, dict[str, SchemeVariant]] = {}
    code_counter = 1
    for scheme, code_prefix, start_nav, drift, vol in scheme_configs:
        regular_path = simulate_gbm_series(rng, n_days, start_nav, drift - 0.012, vol)
        direct_path = simulate_gbm_series(rng, n_days, start_nav, drift - 0.004, vol)
        variants_by_scheme[scheme.id] = {}
        for plan, path in (("regular", regular_path), ("direct", direct_path)):
            variant = SchemeVariant(
                scheme_id=scheme.id,
                plan=plan,
                option="growth",
                amfi_code=f"SMP{code_prefix}{plan[:1].upper()}{code_counter:03d}",
                isin=f"SAMPLE-VAR-{code_counter:04d}",
            )
            db.add(variant)
            db.flush()
            variants_by_scheme[scheme.id][plan] = variant
            db.bulk_save_objects([
                NavHistory(scheme_variant_id=variant.id, date=d, nav=round(float(v), 4), source_id=source.id)
                for d, v in zip(days, path)
            ])
            code_counter += 1

    # --- Portfolio snapshots + holdings (equity schemes only) ---
    as_of = days[-1]
    equity_holdings = {
        scheme_bluechip.id: [
            ("Sample Bank Corp Ltd", 9.8), ("Sample Finserve Ltd", 7.2),
            ("Sample IT Solutions Ltd", 8.5), ("Sample Software Systems Ltd", 5.1),
            ("Sample Energy Corp Ltd", 6.4), ("Sample Consumer Goods Ltd", 5.9),
            ("Sample Pharma Ltd", 4.8), ("Sample Engineering Ltd", 4.2),
        ],
        scheme_flexicap.id: [
            ("Sample Bank Corp Ltd", 6.1), ("Sample IT Solutions Ltd", 6.8),
            ("Sample Energy Corp Ltd", 5.5), ("Sample Foods Ltd", 4.9),
            ("Sample Pharma Ltd", 5.3), ("Sample Hospitals Ltd", 4.4),
            ("Sample Infra Ltd", 4.0), ("Sample Refineries Ltd", 3.7),
        ],
        scheme_midcap.id: [
            ("Sample Software Systems Ltd", 7.5), ("Sample Refineries Ltd", 6.2),
            ("Sample Foods Ltd", 5.8), ("Sample Hospitals Ltd", 5.6),
            ("Sample Infra Ltd", 6.9), ("Sample Engineering Ltd", 5.0),
        ],
    }
    debt_holdings = [
        ("Sample Govt Security 7.26% 2033 (Sample Bond)", 42.0),
        ("Sample NBFC Bond Series X (Sample Bond)", 35.5),
    ]

    for scheme_id, holdings in equity_holdings.items():
        snap = PortfolioSnapshot(scheme_id=scheme_id, as_of_date=as_of, source_id=source.id)
        db.add(snap)
        db.flush()
        db.add_all([
            PortfolioHolding(snapshot_id=snap.id, security_id=securities[name].id, weight_pct=w)
            for name, w in holdings
        ])

    snap_debt = PortfolioSnapshot(scheme_id=scheme_debt.id, as_of_date=as_of, source_id=source.id)
    db.add(snap_debt)
    db.flush()
    db.add_all([
        PortfolioHolding(snapshot_id=snap_debt.id, security_id=securities[name].id, weight_pct=w)
        for name, w in debt_holdings
    ])

    # --- Market regimes ---
    # Illustrative only, derived from qualitative shape of *this synthetic*
    # timeline (not a claim about real historical market regimes — real
    # regime classification is Phase 10 work against real index data).
    db.add_all([
        MarketRegime(name="Sample Regime — Recovery/Bull", regime_type="bull",
                     start_date=NAV_START_DATE, end_date=date(2022, 1, 31)),
        MarketRegime(name="Sample Regime — Correction", regime_type="correction",
                     start_date=date(2022, 2, 1), end_date=date(2022, 7, 31)),
        MarketRegime(name="Sample Regime — High Volatility", regime_type="high_volatility",
                     start_date=date(2022, 8, 1), end_date=date(2023, 3, 31)),
        MarketRegime(name="Sample Regime — Bull", regime_type="bull",
                     start_date=date(2023, 4, 1), end_date=NAV_END_DATE),
    ])

    db.commit()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reset", action="store_true", help="delete previously seeded sample rows first")
    args = parser.parse_args()

    db = SessionLocal()
    try:
        if args.reset:
            reset_sample_data(db)
        if already_seeded(db):
            print("Sample data already present — skipping (use --reset to reseed).")
            return
        seed(db)
        print("Seeded sample data: 2 AMCs, 4 schemes, 8 scheme variants, "
              f"{len(business_days(NAV_START_DATE, NAV_END_DATE))} business days of synthetic NAV/benchmark history.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
