"""Response schema for the Phase 12 AI Explanation Layer."""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from app.schemas.funds import DISCLAIMER

AI_DISCLAIMER = (
    "This summary was generated by an AI model from the structured figures shown in "
    "facts_used only — it does not perform any calculation itself, and every number it "
    "states is verified against those figures before being shown. It is a plain-language "
    "restatement of historical data, not financial advice or a prediction of future results."
)


class AISummaryResponse(BaseModel):
    available: bool
    reason: str | None
    summary: str | None
    facts_used: dict[str, Any]
    ai_disclaimer: str = AI_DISCLAIMER
    disclaimer: str = DISCLAIMER
