"""phase 2 core schema

Revision ID: 9466d1d8bcc7
Revises: 
Create Date: 2026-09-11 17:26:18.278256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9466d1d8bcc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('analytics_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analytics_version', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('index_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fund_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=50), nullable=True),
    sa.Column('horizon_years', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_regimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('regime_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('benchmark_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benchmark_id', 'date', name='uq_benchmark_date')
    )
    op.create_table('data_ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_downloaded', sa.Integer(), nullable=False),
    sa.Column('records_accepted', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amc_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amc_id'], ['amcs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amc_id', 'name', name='uq_fund_family_amc_name')
    )
    op.create_table('investor_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investor_profile_id'], ['investor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('portfolio_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('analysis_json', sa.String(), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('analytics_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['investor_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_family_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
    sa.ForeignKeyConstraint(['fund_family_id'], ['fund_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_manager_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['fund_managers.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'as_of_date', name='uq_snapshot_scheme_date')
    )
    op.create_table('scheme_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('option', sa.String(length=20), nullable=False),
    sa.Column('amfi_code', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("option in ('growth', 'idcw')", name='ck_variant_option'),
    sa.CheckConstraint("plan in ('direct', 'regular')", name='ck_variant_plan'),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amfi_code'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('fund_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_variant_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('analytics_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['scheme_variant_id'], ['scheme_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_variant_id', 'metric_name', 'calc_date', 'analytics_version', name='uq_metric_identity')
    )
    op.create_table('investor_portfolio_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('scheme_variant_id', sa.Integer(), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('invested_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['investor_portfolios.id'], ),
    sa.ForeignKeyConstraint(['scheme_variant_id'], ['scheme_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nav_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_variant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nav > 0', name='ck_nav_positive'),
    sa.ForeignKeyConstraint(['scheme_variant_id'], ['scheme_variants.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_variant_id', 'date', name='uq_nav_variant_date')
    )
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('weight_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.CheckConstraint('weight_pct >= 0 AND weight_pct <= 100', name='ck_weight_pct_range'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['portfolio_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_holdings')
    op.drop_table('nav_history')
    op.drop_table('investor_portfolio_holdings')
    op.drop_table('fund_metrics')
    op.drop_table('scheme_variants')
    op.drop_table('portfolio_snapshots')
    op.drop_table('fund_manager_history')
    op.drop_table('schemes')
    op.drop_table('portfolio_analysis')
    op.drop_table('securities')
    op.drop_table('investor_portfolios')
    op.drop_table('fund_families')
    op.drop_table('data_ingestion_runs')
    op.drop_table('benchmark_history')
    op.drop_table('sectors')
    op.drop_table('market_regimes')
    op.drop_table('investor_profiles')
    op.drop_table('fund_managers')
    op.drop_table('data_sources')
    op.drop_table('benchmarks')
    op.drop_table('analytics_runs')
    op.drop_table('amcs')
    # ### end Alembic commands ###
