"""phase 7 add security market cap category

Revision ID: ffdc020aba6f
Revises: 9466d1d8bcc7
Create Date: 2026-09-12 02:59:17.199234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdc020aba6f'
down_revision: Union[str, Sequence[str], None] = '9466d1d8bcc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('market_cap_category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate doesn't detect CheckConstraints — added manually.
    op.create_check_constraint(
        'ck_security_market_cap_category',
        'securities',
        "market_cap_category in ('large_cap', 'mid_cap', 'small_cap', 'other')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_security_market_cap_category', 'securities', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('securities', 'market_cap_category')
    # ### end Alembic commands ###
